name: Build & Push

# on: [push, pull_request]
on:
  push:
    branches:
      - master
      - feature-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - feature-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build and push docker image to own registry
      uses: dfinance/gh-actions@master
      with:
        name: dfinance/dnode
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}
        dockerfile: ./build/Dockerfile
        build_params: --build-arg CI_PIPELINE_ID=${GITHUB_RUN_ID} --build-arg CI_COMMIT_REF_NAME=${GITHUB_REF} --build-arg CI_COMMIT_SHA=${GITHUB_SHA}
        registry: registry.wings.ai
        cache: true
